services:
  web:
    build: .
    container_name: envanter-app
    ports:
      - "8000:8000"
    volumes:
      # Sadece bir klasörü (data) eşleştiriyoruz. 
      # Böylece sistem ilk açıldığında boş bir veritabanı dosyasını kendisi otomatik oluşturacak.
      - ./data:/app/data
    restart: unless-stopped